; iGate APRS - LILYGO T3 V1.6.1
[env:lilygo-t3-v1]
platform  = espressif32
board     = ttgo-lora32-v1
framework = arduino

;   Puerto serial                       
monitor_speed   = 115200
upload_speed    = 921600

;   Librerías                         
lib_deps =
    jgromes/RadioLib @ ^6.6.0       ; LoRa SX1276/SX1278
    olikraus/U8g2    @ ^2.35.9      ; OLED SSD1306 I2C
    ; WiFi, WiFiClient y Preferences
    ; vienen incluidas con el framework ESP32 Arduino

;   Opciones de compilación                  
build_flags =
    -DCORE_DEBUG_LEVEL=1            ; logs de error en serial
    -DBOARD_HAS_PSRAM=0

;   Partición de flash                    
board_build.partitions = default.csv